spring:
  datasource:
    url: jdbc:postgreSQL://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: MTMt3Rid1984/

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  #h2:
    #console:
      #enabled: true

#jwt:
  #secret: demo-secret-key
