#spring:
#  datasource:
#    url: jdbc:postgreSQL://localhost:5432/Card Payment Request Management
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: PIzza52$$
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#  sql:
#    init:
#      mode: never

  #h2:
    #console:
      #enabled: true

#jwt:
  #secret: demo-secret-key
